name: mpflutter_gamemo
description: The gallery of MPFlutter
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.2.0
  cupertino_icons: ^1.0.6
  go_router: ^13.0.0
  logging: ^1.2.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  mpflutter_core: any
  mpflutter_build_tools: any
  mpflutter_wegame_api: any

dependency_overrides: 
  audioplayers_web:
    git: 
      url: https://github.com/mpflutter/audioplayers.git
      ref: mpflutter-v5.2.1
      path: packages/audioplayers_web

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Bold.ttf
    - family: Noto Sans SC
      fonts:
        - asset: fonts/NotoSansSC-Regular.ttf
    - family: Permanent Marker
      fonts:
        - asset: assets/fonts/Permanent_Marker/PermanentMarker-Regular.ttf
  # shaders:
  #   - shaders/simple.frag
  assets:
    # - assets/
    - assets/images/
    - assets/music/
    - assets/sfx/
